# Generated by Django 3.2.5 on 2021-07-16 03:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210715_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='deposit_at',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='enabled_at',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='withdrawl_at',
        ),
        migrations.AddField(
            model_name='deposit',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
