# Generated by Django 3.2.5 on 2021-07-16 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210716_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='status',
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wallet',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawn_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
