# Generated by Django 3.2.5 on 2021-07-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210716_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='deposit_at',
            new_name='deposited_at',
        ),
    ]
